#include "std_headers.h"

extern int MedianArraysMain();
extern void longestpalindromeMain();
extern void zigzagConcervion();
extern void reverseInteger();
extern void myAtoiMain();
extern void numberPalindromeTest();
extern void regularExpressionMain();
extern void maxAreaMain();
extern void integerToRoman();
extern void roman2Int();
extern void longestCommonPrefix();
extern void threeSumMain();
extern void threeSumClosestMain();
extern void validParentheses();
extern void mergeLists();
extern void mergeKLists();
extern void reverseKnodesMain();
extern void removeDuplicatesMain();
extern void divideMain();
extern void strStrMain();
extern void ssCatMain();
extern void genParenthesesMain();
extern void nextPerMain();
extern void rotSortedArrMain();
extern void searchRangeMain();
extern void combinationSumMain();
extern void countSayMain();
extern void phoneNumbersMain();
extern void firstMissingPosMain();
extern void multiplyStringsMain();
extern void permMain();
extern void perm2Main();
extern void rotateImageMain();
extern void groupAnagramMain();
extern void powerMain();
extern void NQueensMain();
extern void NQueens2Main();
extern void jumpGame2Main();
extern void fourSumMain();
extern int validStringMain();
extern void maxSubarrayMain();
extern void jumpGameMain();
extern void permSeqMain();
extern void textJustificationMain();
extern void validNumbersMain();
extern void simplifyPathMain();
extern void climbStairsMain();
extern void setMatZeroesMain();
extern void set2DMatrixMain();
extern void minWindMain();
extern void combinationMain();
extern void wordSearchMain();
extern void ssdMain();
extern void resIPMain();
extern void uniqueBSTMain();
extern void interleavingStringsMain();
extern void scrambledStringMain();

int main() {
	Heap<int> maxHeap;
	scrambledStringMain();
	return 0;
}